name: TestKCFCSS
on:
  workflow_dispatch:
  
env:
  GIT_ACCESS_TOKEN: "1235456" #this should be replaced with a secret

jobs:
  buildImage:
    permissions:
      contents: read
      id-token: write
    runs-on: runnerhosted
    steps:                        
    # Checkout
    - name: Checkout
      run: | 
        rm -rf TestRunner
        git clone https://github.com/Conduent-Inc/TestRunner.git                   
        ls        
